language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush
 - phpenv rehash
 - drush dl --yes drupal
 - cd drupal-*
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes