language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/ci/setup
  - bash scripts/build
  - cd www
  - sudo chmod 777 -R sites/default/files
  - drush si opengizra --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin --yes
  - drush cc all --yes
  - cd ..

  # Create a behat configuration file.
  - cd opengizra/behat
  - cp behat.local.yml.travis behat.local.yml

  # Create Drush alias.
  - cp aliases.drushrc.php ~/.drush/
  - composer install

script:
  - sudo drush @opengizra runserver --server=builtin 80 &
  - ./bin/behat

